### ISSUE TITLE
Java.lang.NoClassDefFoundError: scala/collection/GenTraversableOnce

### ISSUE THREAD

**Issue by robbyki** [slack-scala-client/slack-scala-client#65]
Tried several different scenarios but still getting this error. Using spark 2.1 with scala 2.11.7 and play-json 2.11.

**Comment by mccartney** [comment]
Works fine with my scala 2.11.8 here.

**Comment by mccartney** [comment]
I am gonna close it until some more context information is provided or steps to reproduce.
